0,NameError,name 'ratings' is not defined,0,,2023-05-25 21:42:56.615725,"[('burritos = ratings', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/3423107744.py"", line 1, in <module>', '    burritos = ratings', ""NameError: name 'ratings' is not defined""]"
1,NameError,name 'burritos' is not defined,0,,2023-05-25 21:47:58.422110,"[('burritos = ratings.join(""Name"", burritos, ""Name"")', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/3672640289.py"", line 1, in <module>', '    burritos = ratings.join(""Name"", burritos, ""Name"")', ""NameError: name 'burritos' is not defined""]"
2,TypeError,Table.scatter() missing 1 required positional argument: 'column_for_x',0,,2023-05-25 21:52:31.418611,"[('yelp_and_google.scatter()', 2)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/4249047126.py"", line 2, in <module>', '    yelp_and_google.scatter()', ""TypeError: Table.scatter() missing 1 required positional argument: 'column_for_x'""]"
3,SyntaxError,"'(' was never closed (3070492844.py, line 1)",0,,2023-05-25 21:59:04.623572,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_2302/3070492844.py"", line 1', '    california_burritos = burritos.select(""Name"", ""Overall"").where(""Name"", contains(""California"")', '                                                                  ^', ""SyntaxError: '(' was never closed""]"
4,SyntaxError,"'(' was never closed (2583604558.py, line 1)",0,,2023-05-25 22:00:26.720770,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_2302/2583604558.py"", line 1', '    california_burritos = burritos.select(""Name"", ""Overall"").where(""Name"", are.containing(""California"")', '                                                                  ^', ""SyntaxError: '(' was never closed""]"
5,ValueError,"label ""Menu_Item"" not in labels ('Name', 'Overall')",0,,2023-05-25 22:02:55.726291,"[('california_burritos = burritos.select(""Name"", ""Overall"").where(""Menu_Item"", are.containing(""California"")).group(""Menu_Item"", np.mean)', 1), ('column = self._get_column(column_or_label)', 1404)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/3375464251.py"", line 1, in <module>', '    california_burritos = burritos.select(""Name"", ""Overall"").where(""Menu_Item"", are.containing(""California"")).group(""Menu_Item"", np.mean)', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 1404, in where', '    column = self._get_column(column_or_label)', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 2209, in _get_column', '    raise ValueError(\'label ""{}"" not in labels {}\'.format(c, self.labels))', 'ValueError: label ""Menu_Item"" not in labels (\'Name\', \'Overall\')']"
6,SyntaxError,"incomplete input (3668580642.py, line 3)",0,,2023-05-25 22:12:47.946599,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_2302/3668580642.py"", line 3', '    burritos.where(""Menu_Item"", are.containing(""San Diego"").select(""Menu_Item"", ""Cost"").hist(""Cost"", bins=bins)', '                                                                                                               ^', 'SyntaxError: incomplete input']"
7,SyntaxError,"invalid syntax (595875793.py, line 1)",0,,2023-05-25 22:20:11.102785,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_2302/595875793.py"", line 1', '    burritos_less_than_6 = 23%', '                              ^', 'SyntaxError: invalid syntax']"
8,TypeError,column functions must be callable,0,,2023-05-25 22:43:32.208528,"[('job_titles = sf.select(""Job"", ""Organization Group"").group(""Organization Group"", ""first_item"")', 11), ('collect = _zero_on_type_error(collect)', 1556)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/3920379073.py"", line 11, in <module>', '    job_titles = sf.select(""Job"", ""Organization Group"").group(""Organization Group"", ""first_item"")', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 1556, in group', '    collect = _zero_on_type_error(collect)', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 5828, in _zero_on_type_error', ""    raise TypeError('column functions must be callable')"", 'TypeError: column functions must be callable']"
9,SyntaxError,"unterminated string literal (detected at line 5) (482606735.py, line 5)",0,,2023-05-25 22:58:09.614282,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_2302/482606735.py"", line 5', '    department_ranges = sf.pivot(""Department"", """"Organization Group"", ""Total Compensation"", compensation_range)', '                                                                                         ^', 'SyntaxError: unterminated string literal (detected at line 5)']"
10,ValueError,"label ""Total Compensation"" not in labels ('Department', 'Total Compensation average')",0,,2023-05-25 23:08:43.583696,"[('num_over_125k = len(avg_of_depts.where(""Total Compensation"", are.above(125000)).column(""Department""))', 3), ('column = self._get_column(column_or_label)', 1404)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/1996495396.py"", line 3, in <module>', '    num_over_125k = len(avg_of_depts.where(""Total Compensation"", are.above(125000)).column(""Department""))', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 1404, in where', '    column = self._get_column(column_or_label)', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 2209, in _get_column', '    raise ValueError(\'label ""{}"" not in labels {}\'.format(c, self.labels))', 'ValueError: label ""Total Compensation"" not in labels (\'Department\', \'Total Compensation average\')']"
11,AttributeError,'NoneType' object has no attribute 'where',0,,2023-05-25 23:10:00.270702,"[('num_over_125k = len(avg_of_depts.where(""Total Compensation average"", are.above(125000)).column(""Department""))', 3)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_2302/4275592159.py"", line 3, in <module>', '    num_over_125k = len(avg_of_depts.where(""Total Compensation average"", are.above(125000)).column(""Department""))', ""AttributeError: 'NoneType' object has no attribute 'where'""]"
