0,TypeError,unsupported operand type(s) for +: 'int' and 'str',0,,2023-05-20 17:58:35.281013,"[('8 + ""8""', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_5348/451511607.py"", line 1, in <module>', '    8 + ""8""', ""TypeError: unsupported operand type(s) for +: 'int' and 'str'""]"
1,TypeError,unsupported operand type(s) for +: 'int' and 'str',0,,2023-05-20 18:07:29.252402,"[('8 + ""8""', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_5348/451511607.py"", line 1, in <module>', '    8 + ""8""', ""TypeError: unsupported operand type(s) for +: 'int' and 'str'""]"
2,IndexError,index 66 is out of bounds for axis 0 with size 66,0,,2023-05-20 18:28:12.683079,"[('population_2016 = population_amounts.item(66)', 3)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_5348/4056345982.py"", line 3, in <module>', '    population_2016 = population_amounts.item(66)', 'IndexError: index 66 is out of bounds for axis 0 with size 66']"
3,NameError,name 'restaurant' is not defined,0,,2023-05-20 19:07:49.153637,"[('total_charges = restaurant', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_5348/3376928587.py"", line 1, in <module>', '    total_charges = restaurant', ""NameError: name 'restaurant' is not defined""]"
