0,SyntaxError,"incomplete input (1867411798.py, line 1)",0,,2023-05-08 12:51:33.902852,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_809/1867411798.py"", line 1', '    print(""This line is missing something.""', '                                           ^', 'SyntaxError: incomplete input']"
1,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-05-08 12:53:08.670195,"[('grader.check(""q5_1_1"")', 1), ('raise e', 194)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_809/3591509398.py"", line 1, in <module>', '    grader.check(""q5_1_1"")', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 194, in event_logger', '    raise e', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 185, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
2,SyntaxError,"incomplete input (1867411798.py, line 1)",0,,2023-05-08 16:43:40.615323,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_11966/1867411798.py"", line 1', '    print(""This line is missing something.""', '                                           ^', 'SyntaxError: incomplete input']"
3,NameError,name 'eleven' is not defined,0,,2023-05-08 16:52:56.308405,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_11966/1097191323.py"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
