0,SyntaxError,"'(' was never closed (154454075.py, line 1)",0,,2023-05-08 12:22:44.060912,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_10555/154454075.py"", line 1', '    new_year = (max(abs(pow(2, 5) - pow(2, 11) - pow(2, 1)), 5 * 13 *31 + 7)', '               ^', ""SyntaxError: '(' was never closed""]"
1,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-05-08 12:23:21.588231,"[('grader.check(""q11"")', 1), ('raise e', 194)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_10555/2079648672.py"", line 1, in <module>', '    grader.check(""q11"")', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 194, in event_logger', '    raise e', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 185, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
2,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-05-08 12:27:08.676870,"[('grader.check(""q11"")', 1), ('raise e', 194)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_10555/2079648672.py"", line 1, in <module>', '    grader.check(""q11"")', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 194, in event_logger', '    raise e', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 185, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
3,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-05-08 12:27:56.115274,"[('grader.check(""q21"")', 1), ('raise e', 194)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_10555/1223131607.py"", line 1, in <module>', '    grader.check(""q21"")', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 194, in event_logger', '    raise e', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/utils.py"", line 185, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/conda/lib/python3.10/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
4,ValueError,"The column ""name"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time",0,,2023-05-08 15:19:51.635371,"[('farmers_markets_locations = farmers_markets.select(""name"", ""city"", ""state"", ""latitude"", ""longitude"")', 1), ('self._add_column_and_format(table, label, np.copy(self[label]))', 1252)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_1869/338577401.py"", line 1, in <module>', '    farmers_markets_locations = farmers_markets.select(""name"", ""city"", ""state"", ""latitude"", ""longitude"")', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 1252, in select', '    self._add_column_and_format(table, label, np.copy(self[label]))', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 261, in __getitem__', '    return self.column(index_or_label)', '  File ""/opt/conda/lib/python3.10/site-packages/datascience/tables.py"", line 408, in column', '    raise ValueError(', 'ValueError: The column ""name"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time']"
5,AttributeError,type object 'are' has no attribute 'equalTo',0,,2023-05-08 15:25:53.918009,"[(""berkeley_markets = california_farmers_markets.where('city', are.equalTo('Berkeley'))"", 1)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_1869/3361636609.py"", line 1, in <module>', ""    berkeley_markets = california_farmers_markets.where('city', are.equalTo('Berkeley'))"", ""AttributeError: type object 'are' has no attribute 'equalTo'""]"
6,SyntaxError,"unterminated string literal (detected at line 1) (686197480.py, line 1)",0,,2023-05-08 15:30:05.860818,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_1869/686197480.py"", line 1', ""    above_eight = imdb.where('Year', are_between_or_equal_to(2010, 2015).where('Rating', are.above(8)).select(''Title', 'Rating')"", '                                                                                                                               ^', 'SyntaxError: unterminated string literal (detected at line 1)']"
7,SyntaxError,"unterminated string literal (detected at line 1) (1549195023.py, line 1)",0,,2023-05-08 15:32:22.053987,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_1869/1549195023.py"", line 1', ""    above_eight = imdb.where('Year', are_between_or_equal_to(2010, 2015)).where('Rating', are.above(8)).select(''Title', 'Rating')"", '                                                                                                                                ^', 'SyntaxError: unterminated string literal (detected at line 1)']"
8,SyntaxError,"unterminated string literal (detected at line 1) (461256116.py, line 1)",0,,2023-05-08 15:32:36.180999,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3241, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_1869/461256116.py"", line 1', ""    above_eight = imdb.where('Year', are.between_or_equal_to(2010, 2015)).where('Rating', are.above(8)).select(''Title', 'Rating')"", '                                                                                                                                ^', 'SyntaxError: unterminated string literal (detected at line 1)']"
9,AttributeError,type object 'are' has no attribute 'greater_than_or_equal_to',0,,2023-05-08 15:36:43.000450,"[(""num_in_21st_century = imdb.where('Year', are.greater_than_or_equal_to(2000))"", 3)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_1869/224359434.py"", line 3, in <module>', ""    num_in_21st_century = imdb.where('Year', are.greater_than_or_equal_to(2000))"", ""AttributeError: type object 'are' has no attribute 'greater_than_or_equal_to'""]"
10,TypeError,unsupported operand type(s) for /: 'Table' and 'int',0,,2023-05-08 15:37:11.284243,"[('proportion_in_20th_century = num_in_20th_century / num_movies_in_dataset', 4)]","['Traceback (most recent call last):', '  File ""/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3508, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_1869/2321224795.py"", line 4, in <module>', '    proportion_in_20th_century = num_in_20th_century / num_movies_in_dataset', ""TypeError: unsupported operand type(s) for /: 'Table' and 'int'""]"
